import { BRAND, absoluteLogoUrl } from '@/lib/brand';
import { absoluteUrl } from '@/lib/site';

export const DEFAULT_GALLERY_CATEGORIES = [
  { id: 'residential', name: 'Residential', slug: 'residential', displayOrder: 1, active: true },
  { id: 'commercial', name: 'Commercial', slug: 'commercial', displayOrder: 2, active: true },
  { id: 'rental-interiors', name: 'Rental Furnishing', slug: 'rental-interiors', displayOrder: 3, active: true },
  { id: 'modular-solutions', name: 'Modular Solutions', slug: 'modular-solutions', displayOrder: 4, active: true },
  { id: 'renovation', name: 'Renovation', slug: 'renovation', displayOrder: 5, active: true },
  { id: 'styling', name: 'Styling', slug: 'styling', displayOrder: 6, active: true },
  { id: 'turnkey-projects', name: 'Turnkey Projects', slug: 'turnkey-projects', displayOrder: 7, active: true },
];

export const DEFAULT_SERVICES = [
  {
    id: 'residential-interiors',
    slug: 'residential-interiors',
    name: 'Residential Interiors',
    shortDescription: 'Complete home interior design and execution for apartments, villas and penthouses across Mumbai.',
    description: 'End-to-end residential interior solutions — from concept and 3D visualization to modular execution, furniture and final styling.',
    heroImage: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Space planning', 'Material curation', 'Modular execution', 'Turnkey handover'],
    icon: 'Home',
    priceLabel: 'Custom quote',
    displayOrder: 1,
    active: true,
    categoryId: 'residential',
  },
  {
    id: 'commercial-interiors',
    slug: 'commercial-interiors',
    name: 'Commercial Interiors',
    shortDescription: 'Office, retail and hospitality interiors designed for brand identity and operational efficiency.',
    description: 'Professional commercial interior design for offices, retail stores, restaurants and hospitality spaces with on-time delivery.',
    heroImage: 'https://images.unsplash.com/photo-1497366216548-37526070297c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Brand-aligned design', 'Workflow optimization', 'Premium finishes', 'Project management'],
    icon: 'Building2',
    priceLabel: 'Custom quote',
    displayOrder: 2,
    active: true,
    categoryId: 'commercial',
  },
  {
    id: 'rental-interiors',
    slug: 'rental-interiors',
    name: 'Rental Furnishing',
    shortDescription: 'Investor-ready rental apartments styled for faster occupancy and higher rental yield.',
    description: 'Dedicated rental interior solutions — furnished conversions, Airbnb setups, budget packages and tenant move-in solutions.',
    heroImage: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?crop=entropy&cs=srgb&fm=mp&q=85&w=1200',
    galleryImages: [],
    features: ['Ready-to-rent packages', 'Airbnb setup', 'Budget furnishing', 'Investor styling'],
    icon: 'Home',
    priceLabel: 'Packages from ₹2.5L',
    displayOrder: 3,
    active: true,
    categoryId: 'rental-interiors',
    isRentalModule: true,
  },
  {
    id: 'modular-kitchens',
    slug: 'modular-kitchens',
    name: 'Modular Kitchens',
    shortDescription: 'Custom L-shaped, parallel and island kitchens with premium hardware and finishes.',
    description: 'Precision-engineered modular kitchens designed for Mumbai homes — acrylic, PU and laminate finishes with German hardware.',
    heroImage: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Custom layouts', 'Premium hardware', 'Soft-close fittings', '5-year warranty'],
    icon: 'Sparkles',
    priceLabel: 'From ₹1.2L',
    displayOrder: 4,
    active: true,
    categoryId: 'modular-solutions',
  },
  {
    id: 'modular-wardrobes',
    slug: 'modular-wardrobes',
    name: 'Modular Wardrobes',
    shortDescription: 'Sliding, hinged and walk-in wardrobes with custom interiors and premium finishes.',
    description: 'Space-maximizing wardrobe solutions with Hettich & Hafele hardware, custom compartments and premium laminate/acrylic finishes.',
    heroImage: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Sliding & hinged', 'Walk-in designs', 'Custom interiors', 'Premium hardware'],
    icon: 'Layers',
    priceLabel: 'From ₹45,000',
    displayOrder: 5,
    active: true,
    categoryId: 'modular-solutions',
  },
  {
    id: 'renovation-remodeling',
    slug: 'renovation-remodeling',
    name: 'Renovation & Remodeling',
    shortDescription: 'Complete home renovation with structural, civil and interior upgrades under one team.',
    description: 'Full-scale renovation and remodeling — kitchen upgrades, bathroom remodels, layout changes and complete home transformations.',
    heroImage: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Civil work', 'Layout changes', 'Material upgrades', 'Phased execution'],
    icon: 'Hammer',
    priceLabel: 'Custom quote',
    displayOrder: 6,
    active: true,
    categoryId: 'renovation',
  },
  {
    id: 'turnkey-projects',
    slug: 'turnkey-projects',
    name: 'Turnkey Projects',
    shortDescription: 'Single-point design-to-execution for complete interior projects with fixed timelines.',
    description: 'End-to-end turnkey interior execution — design, procurement, modular work, furniture, styling and handover under one contract.',
    heroImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Single contract', 'Fixed timeline', 'Quality control', 'Warranty-backed'],
    icon: 'BadgeCheck',
    priceLabel: 'Custom quote',
    displayOrder: 7,
    active: true,
    categoryId: 'turnkey-projects',
  },
  {
    id: 'space-planning',
    slug: 'space-planning',
    name: 'Space Planning',
    shortDescription: 'Expert layout optimization to maximize flow, light and function in every room.',
    description: 'Professional space planning with 2D/3D layouts, circulation analysis and furniture placement for optimal living.',
    heroImage: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['2D/3D layouts', 'Flow optimization', 'Furniture planning', 'Light analysis'],
    icon: 'Layout',
    priceLabel: 'From ₹2,999',
    displayOrder: 8,
    active: true,
    categoryId: 'residential',
  },
  {
    id: 'interior-styling',
    slug: 'interior-styling',
    name: 'Interior Styling',
    shortDescription: 'Curated decor, soft furnishings and accent styling to elevate your space.',
    description: 'Professional interior styling with furniture curation, art placement, soft furnishings and accessorizing for a magazine-ready finish.',
    heroImage: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Furniture curation', 'Soft furnishings', 'Art & decor', 'Seasonal refresh'],
    icon: 'Sparkles',
    priceLabel: 'Custom quote',
    displayOrder: 9,
    active: true,
    categoryId: 'styling',
  },
  {
    id: 'design-consultation',
    slug: 'design-consultation',
    name: 'Design Consultation',
    shortDescription: 'Professional design consultation for material, layout and aesthetic decisions.',
    description: 'Expert interior design consultation — material selection, color palettes, layout advice and vendor recommendations.',
    heroImage: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    galleryImages: [],
    features: ['Material guidance', 'Color palettes', 'Layout advice', 'Vendor connect'],
    icon: 'Sparkles',
    priceLabel: 'From ₹2,999',
    displayOrder: 10,
    active: true,
    categoryId: 'residential',
  },
];

export const DEFAULT_RENTAL_SUB_SERVICES = [
  { id: 'rental-apartment-setup', name: 'Rental Apartment Setup', description: 'Complete furnishing and styling for rental apartments ready for tenant move-in.', displayOrder: 1, active: true },
  { id: 'investor-property-furnishing', name: 'Investor Property Furnishing', description: 'Turnkey furnishing for investor properties targeting premium rental yields.', displayOrder: 2, active: true },
  { id: 'ready-to-rent-packages', name: 'Ready-To-Rent Packages', description: 'Fixed-budget packages with furniture, appliances and decor for immediate rental.', displayOrder: 3, active: true },
  { id: 'furnished-rental-conversion', name: 'Furnished Rental Conversion', description: 'Convert unfurnished units into fully furnished rental-ready homes.', displayOrder: 4, active: true },
  { id: 'airbnb-setup-solutions', name: 'Airbnb Setup Solutions', description: 'Guest-ready interiors optimized for short-term rental and hospitality standards.', displayOrder: 5, active: true },
  { id: 'budget-rental-packages', name: 'Budget Rental Packages', description: 'Cost-effective furnishing packages for budget-conscious rental investors.', displayOrder: 6, active: true },
  { id: 'tenant-move-in-solutions', name: 'Tenant Move-In Solutions', description: 'Quick turnaround furnishing for corporate and individual tenant requirements.', displayOrder: 7, active: true },
  { id: 'rental-property-styling', name: 'Rental Property Styling', description: 'Professional styling to maximize appeal and rental value of your property.', displayOrder: 8, active: true },
];

export const DEFAULT_ABOUT_CONTENT = {
  id: 'main',
  enabled: true,
  displayOrder: 1,
  companyIntroduction: `${BRAND.name} is a premium interior design and interior solutions company based in Mumbai. We deliver design-to-execution projects for residential, commercial and rental properties — from modular kitchens and wardrobes to complete turnkey transformations.`,
  founderMessage: 'We founded CraftSquare Studio with a simple belief: every Mumbai home deserves world-class interior design without the chaos of managing multiple contractors. One team, one vision, one seamless experience.',
  mission: 'To deliver exceptional interior design and execution that transforms spaces into functional, beautiful environments — on time and within budget.',
  vision: 'To become Mumbai\'s most trusted design-to-execution interior solutions brand, known for quality, transparency and customer delight.',
  coreValues: [
    { title: 'Design Excellence', text: 'Every project begins with thoughtful design and meticulous planning.' },
    { title: 'Transparent Process', text: 'Clear timelines, digital quotations and regular progress updates.' },
    { title: 'Quality Execution', text: 'Premium materials, skilled teams and rigorous quality checks.' },
    { title: 'Customer First', text: 'Your vision drives every decision from concept to handover.' },
  ],
  whyChooseUs: [
    { title: 'Design-to-Execution', text: 'Single team handles design, modular work, furniture and final styling.' },
    { title: 'Premium Materials', text: 'Curated materials and hardware from trusted global and Indian brands.' },
    { title: 'Dedicated Manager', text: 'One project owner for quote, schedule, execution and handover.' },
    { title: 'Digital Quotation', text: 'Transparent scope, material recommendation and timeline in writing.' },
    { title: 'Real-Time Tracking', text: 'Project status updates from design approval to final handover.' },
    { title: 'Warranty-Backed', text: 'Structural warranty on modular work and workmanship guarantee.' },
  ],
  experienceYears: '12+',
  teamDescription: 'Our team of interior designers, project managers and skilled execution teams bring together decades of experience in Mumbai\'s residential and commercial interior market.',
  achievementCounters: [
    { label: 'Projects delivered', value: '850+', icon: 'Home' },
    { label: 'Average rating', value: '4.9/5', icon: 'Star' },
    { label: 'Years of experience', value: '12+', icon: 'Award' },
    { label: 'Design consultants', value: '25+', icon: 'Users' },
  ],
  images: [
    { url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?crop=entropy&cs=srgb&fm=jpg&q=85&w=800', alt: 'CraftSquare Studio interior project' },
    { url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?crop=entropy&cs=srgb&fm=jpg&q=85&w=800', alt: 'Modern living room design' },
  ],
  certifications: [
    { name: 'ISO Quality Standards', description: 'Quality management aligned with industry best practices.' },
    { name: 'Modular Partner Network', description: 'Authorized partnerships with premium modular manufacturers.' },
  ],
  homepageEyebrow: 'About Us',
  homepageTitle: 'Designing spaces that inspire living',
  homepageSubtitle: 'Mumbai\'s trusted design-to-execution interior solutions partner.',
};

export const DEFAULT_GALLERY_ITEMS = [
  {
    id: 'proj-residential-1',
    title: '3BHK Premium Interior, Bandra',
    slug: '3bhk-premium-interior-bandra',
    description: 'Complete residential transformation with modular kitchen, custom wardrobes and curated styling.',
    categoryId: 'residential',
    category: 'Residential',
    mediaType: 'image',
    imageUrl: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?crop=entropy&cs=srgb&fm=jpg&q=85&w=600',
    location: 'Bandra West, Mumbai',
    duration: '45 days',
    result: 'Turnkey interior with premium finishes and warranty',
    featured: true,
    displayOrder: 1,
    active: true,
  },
  {
    id: 'proj-commercial-1',
    title: 'Corporate Office Interior, Andheri',
    slug: 'corporate-office-andheri',
    description: 'Modern office interior with open-plan workstations, meeting rooms and brand-aligned reception.',
    categoryId: 'commercial',
    category: 'Commercial',
    mediaType: 'image',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?crop=entropy&cs=srgb&fm=jpg&q=85&w=600',
    location: 'Andheri East, Mumbai',
    duration: '60 days',
    result: 'Productivity-focused workspace with premium finishes',
    featured: true,
    displayOrder: 2,
    active: true,
  },
  {
    id: 'proj-rental-1',
    title: 'Rental Apartment Setup, Powai',
    slug: 'rental-apartment-powai',
    description: 'Investor-ready furnished rental apartment with budget-optimized furniture and decor.',
    categoryId: 'rental-interiors',
    category: 'Rental Interiors',
    mediaType: 'image',
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?crop=entropy&cs=srgb&fm=jpg&q=85&w=600',
    location: 'Powai, Mumbai',
    duration: '14 days',
    result: 'Tenant-ready furnished apartment delivered on schedule',
    featured: true,
    displayOrder: 3,
    active: true,
  },
  {
    id: 'proj-modular-1',
    title: 'Island Modular Kitchen, Juhu',
    slug: 'island-kitchen-juhu',
    description: 'Premium island kitchen with acrylic finish, soft-close hardware and integrated lighting.',
    categoryId: 'modular-solutions',
    category: 'Modular Solutions',
    mediaType: 'image',
    imageUrl: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?crop=entropy&cs=srgb&fm=jpg&q=85&w=600',
    location: 'Juhu, Mumbai',
    duration: '12 days',
    result: 'Luxury acrylic kitchen with 5-year structural warranty',
    featured: false,
    displayOrder: 4,
    active: true,
  },
  {
    id: 'proj-renovation-1',
    title: 'Complete Home Renovation, Thane',
    slug: 'home-renovation-thane',
    description: 'Full-scale renovation including layout changes, new modular kitchen and wardrobe upgrades.',
    categoryId: 'renovation',
    category: 'Renovation',
    mediaType: 'image',
    imageUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?crop=entropy&cs=srgb&fm=jpg&q=85&w=600',
    location: 'Thane, Mumbai MMR',
    duration: '90 days',
    result: 'Complete transformation with phased execution',
    featured: false,
    displayOrder: 5,
    active: true,
  },
  {
    id: 'proj-styling-1',
    title: 'Luxury Home Styling, Pali Hill',
    slug: 'luxury-styling-pali-hill',
    description: 'Curated furniture, soft furnishings and art placement for a premium apartment.',
    categoryId: 'styling',
    category: 'Styling',
    mediaType: 'image',
    imageUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?crop=entropy&cs=srgb&fm=jpg&q=85&w=1200',
    videoUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?crop=entropy&cs=srgb&fm=jpg&q=85&w=600',
    location: 'Pali Hill, Mumbai',
    duration: '21 days',
    result: 'Magazine-ready interior styling with curated decor',
    featured: true,
    displayOrder: 6,
    active: true,
  },
];

export const DEFAULT_SEO_SETTINGS = {
  id: 'main',
  pages: {
    home: {
      metaTitle: `${BRAND.name} | Premium Interior Design & Solutions Mumbai`,
      metaDescription: 'Transform your space with expert interior design, modular kitchens, wardrobes, rental interiors and turnkey execution in Mumbai. Book free consultation today.',
      keywords: ['Interior Design Mumbai', 'Modular Kitchen Mumbai', 'Wardrobe Design Mumbai', 'Rental Interiors Mumbai', 'Turnkey Interiors Mumbai', 'Commercial Interiors Mumbai', 'Home Renovation Mumbai'],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/'),
    },
    about: {
      metaTitle: `About ${BRAND.name} | Interior Design Company Mumbai`,
      metaDescription: 'Learn about CraftSquare Studio — Mumbai\'s premium design-to-execution interior solutions company with 12+ years of experience.',
      keywords: ['About CraftSquare Studio', 'Interior Design Company Mumbai', 'Interior Design Team Mumbai'],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/about'),
    },
    gallery: {
      metaTitle: `Project Gallery | ${BRAND.name} Mumbai`,
      metaDescription: 'Explore our portfolio of residential, commercial, rental and modular interior projects across Mumbai.',
      keywords: ['Interior Design Portfolio Mumbai', 'Home Interior Gallery', 'Modular Kitchen Projects Mumbai'],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/gallery'),
    },
    rentalInteriors: {
      metaTitle: `Rental Interiors | ${BRAND.name} Mumbai`,
      metaDescription: 'Investor-ready rental interior solutions — furnished conversions, Airbnb setups, budget packages and tenant move-in solutions in Mumbai.',
      keywords: ['Rental Interiors Mumbai', 'Furnished Rental Apartment Mumbai', 'Airbnb Setup Mumbai', 'Investor Property Furnishing'],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/rental-interiors'),
    },
    services: {
      metaTitle: `Interior Services | ${BRAND.name} Mumbai`,
      metaDescription: 'Residential, commercial, modular and turnkey interior services from Mumbai\'s trusted design-to-execution studio.',
      keywords: ['Interior Services Mumbai', 'Modular Kitchen Mumbai', 'Interior Renovation Mumbai'],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/#services'),
    },
    shadeExplorer: {
      metaTitle: `Shade Explorer | ${BRAND.name} Mumbai`,
      metaDescription: 'Explore premium paint shades from Asian Paints, Nerolac, Berger and Dulux for your Mumbai interior project.',
      keywords: ['Paint Shades Mumbai', 'Interior Colour Consultation', 'Asian Paints Shades Mumbai'],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/shade-explorer'),
    },
    blog: {
      metaTitle: `Interior Design Blog | ${BRAND.name} Mumbai`,
      metaDescription: 'Expert interior design insights, modular kitchen tips, rental furnishing guides and Mumbai home inspiration from CraftSquare Studio.',
      keywords: ['Interior Design Blog Mumbai', 'Home Decor Tips', 'Modular Kitchen Ideas', BRAND.name],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/blog'),
    },
    estimate: {
      metaTitle: `AI Interior Estimate | ${BRAND.name} Mumbai`,
      metaDescription: 'Get an AI-assisted interior design estimate and personalised recommendations from CraftSquare Studio in Mumbai.',
      keywords: ['AI Interior Estimate', 'Interior Design Quote Mumbai', BRAND.name],
      ogImage: absoluteLogoUrl,
      canonicalUrl: absoluteUrl('/estimate'),
    },
  },
};

export const DEFAULT_FAQS = [
  { q: 'Is the design consultation really free?', a: `${BRAND.name} offers a complimentary initial consultation across Mumbai for residential, commercial and rental interior enquiries.` },
  { q: 'How does the project estimation work?', a: 'Our estimator gives a planning range based on scope, area and finish level. The final quotation is shared after site visit and detailed measurements.' },
  { q: 'Do you provide warranty on your work?', a: 'Yes. Modular kitchens and wardrobes come with a 5-year structural warranty. All eligible interior projects receive a workmanship guarantee.' },
  { q: 'Can I book multiple services together?', a: 'Absolutely. Many clients book modular kitchen + wardrobes + complete interior styling as a turnkey package for better coordination and pricing.' },
  { q: 'How long does a modular kitchen take?', a: 'A typical modular kitchen takes 7–15 working days from order confirmation depending on design complexity and material availability.' },
  { q: 'Can I track my project?', a: 'Yes. Your dedicated project manager provides regular updates from design approval through execution to final handover.' },
  { q: 'Do you handle rental property interiors?', a: 'Yes. We specialize in rental apartment setup, investor furnishing, Airbnb solutions and ready-to-rent packages.' },
  { q: 'What areas in Mumbai do you serve?', a: 'We serve all of Mumbai including Bandra, Andheri, Powai, Juhu, Malad, Kandivali, Borivali, Thane and Navi Mumbai.' },
];

export const DEFAULT_ESTIMATOR_RATES = {
  'residential-interiors': 450,
  'commercial-interiors': 550,
  'rental-interiors': 280,
  'modular-kitchens': 1800,
  'modular-wardrobes': 650,
  'renovation-remodeling': 520,
  'turnkey-projects': 480,
  'space-planning': 35,
  'interior-styling': 120,
  'design-consultation': 25,
};

export const DEFAULT_PRICING_SETTINGS = {
  key: 'pricing',
  services: DEFAULT_SERVICES.map((service) => ({
    id: service.slug,
    title: service.name,
    price: service.priceLabel,
    icon: service.icon,
    description: service.shortDescription,
    active: service.active,
    baseRate: DEFAULT_ESTIMATOR_RATES[service.slug] || 450,
  })),
  qualityMultipliers: { economy: 0.82, standard: 1, premium: 1.28, luxury: 1.65 },
  freshMultiplier: 1.38,
  villaMultiplier: 1.18,
  commercialMultiplier: 1.12,
  materialPercent: 58,
  laborPercent: 34,
  repaintSqftPerDay: 120,
  freshSqftPerDay: 80,
  standardWarranty: '1 year workmanship warranty on eligible interior projects',
  waterproofingWarranty: '5 year structural warranty on modular kitchens and wardrobes',
  updatedAt: null,
};
